/* Database schema to keep the structure of entire database. */
DROP TABLE IF EXISTS animals;

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(80) NOT NULL,
    date_of_birth date,
    escape_attempts int,
    neutered boolean,
    weight_kg real,
    species varchar(80),
    PRIMARY KEY(id)
);