/* Database schema to keep the structure of entire database. */
DROP TABLE IF EXISTS species;
CREATE TABLE species (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(80) NOT NULL,
    PRIMARY KEY(id)
);
DROP TABLE IF EXISTS owners;
CREATE TABLE owners (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    full_name varchar(80) NOT NULL,
    age int,
    PRIMARY KEY(id)
);
DROP TABLE IF EXISTS animals;
CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(80) NOT NULL,
    date_of_birth date,
    escape_attempts int,
    neutered boolean,
    weight_kg real,
    species_id int REFERENCES species,
    owner_id int REFERENCES owners,
    PRIMARY KEY(id)
);